### ISSUE TITLE
gips_tclass classify error

### ISSUE THREAD

**Issue by dchowdhury** [matthewhanson/gips#26]
dchowdhury@nile:/titan/work/dchowdhury/RICE_DSS/SacramentoValley/tile_044033/DROUGHT$ gips_tclass classify site_30.0_Landsat_2012_low/ -t site_30.0_Landsat_2011_train_low/tclass.train.2011001__cdl.10000k/ --nproc 2 -p ndvi-toa lswi-toa satvi-toa -v4

GIPS (v0.8.0rc4): Temporal Classifier (v0.6.0)
Running TCLASS for 1 dates between 2012-05-07 and 2012-05-07
Training...
Error in Temporal Classifier: Array contains NaN or infinity.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gips/algorithm.py", line 106, in main
    alg.run_command(**vars(args))
  File "build/bdist.linux-x86_64/egg/gips/algorithm.py", line 52, in run_command
    exec('self.%s(**kwargs)' % command)
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gipsbin/tclass.py", line 381, in classify
    self.run_dates(self.inv.dates[0:i + 1])
  File "build/bdist.linux-x86_64/egg/gipsbin/tclass.py", line 389, in run_dates
    self.train_dates(dates)
  File "build/bdist.linux-x86_64/egg/gipsbin/tclass.py", line 427, in train_dates
    classifier.fit(tdata, self.truth)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/forest.py", line 257, in fit
    check_ccontiguous=True)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 233, in check_arrays
    _assert_all_finite(array)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 27, in _assert_all_finite
    raise ValueError("Array contains NaN or infinity.")
ValueError: Array contains NaN or infinity.

I had used both training and project dirs previously and they classified just fine. I also checked the projdir images and pruned truth image for NaN/infinity values and didn't find any.

Thanks.

**Comment by ircwaves** [comment]
@dchowdhury -- have you documented this over on bitbucket?

**Comment by dchowdhury** [comment]
I think this issue was fixed.
