### ISSUE TITLE
gips_project/gips_inventory not working on rio

### ISSUE THREAD

**Issue by dchowdhury** [matthewhanson/gips#51]
dchowdhury@rio:/scratch/dchowdhury/VHI$ gips_project modis -h
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/dchowdhury/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/gips_project", line 9, in <module>
    load_entry_point('gips==0.8.1', 'console_scripts', 'gips_project')()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/scripts/project.py", line 41, in main
    args = parser0.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/parsers.py", line 44, in parse_args
    self.add_data_sources()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/parsers.py", line 154, in add_data_sources
    for src, desc in data_sources().items():
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/utils.py", line 207, in data_sources
    raise Exception('ERROR: archive %s is not a directory or is not available' % key)
Exception: ERROR: archive merra is not a directory or is not available

dchowdhury@rio:/scratch/dchowdhury/VHI$ gips_inventory -h
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/dchowdhury/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/gips_inventory", line 9, in <module>
    load_entry_point('gips==0.8.1', 'console_scripts', 'gips_inventory')()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/scripts/inventory.py", line 39, in main
    args = parser0.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/parsers.py", line 44, in parse_args
    self.add_data_sources()
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/parsers.py", line 154, in add_data_sources
    for src, desc in data_sources().items():
  File "/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/utils.py", line 207, in data_sources
    raise Exception('ERROR: archive %s is not a directory or is not available' % key)
Exception: ERROR: archive merra is not a directory or is not available

**Comment by ircwaves** [comment]
This is a settings issue on `rio`.  Should be all set now.
